[Colors]
; Colores base para proyectos específicos (formato #RRGGBB)
; Si un proyecto no está definido aquí, usa el color por defecto (#CCCCCC)
BRDA =rgb(255, 136, 32)
ERSO = #d78ad1
ETDM = #F7DC6F
KTCE = #da8e1b
LC =rgb(118, 202, 122)
MOR = #d53838
PHLDA = #85C1E9
VLLF = #F7DC6F
YM = #F1948A
